// Student data - 100 students with name, roll, sex, blood group
const students = [
    { id: 1, name: "Deamun Muktaref Shrestho", rollNumber: "1", sex: "Male", bloodGroup: "B+" },
    { id: 2, name: "Syeda Anamika Rahman", rollNumber: "2", sex: "Female", bloodGroup: "A+" },
    { id: 3, name: "Anindita Bhowmick", rollNumber: "3", sex: "Female", bloodGroup: "A+" },
    { id: 4, name: "Shorazoom Muneer Khair", rollNumber: "4", sex: "Male", bloodGroup: "A+" },
    { id: 5, name: "Afia Rahman Siddika", rollNumber: "5", sex: "Female", bloodGroup: "O+" },
    { id: 6, name: "Shrestha Chakroborty", rollNumber: "6", sex: "Female", bloodGroup: "O+" },
    { id: 7, name: "Jurain Mahmud Jureen", rollNumber: "7", sex: "Female", bloodGroup: "A+" },
    { id: 8, name: "Nusrat Mehzabeen Sumara", rollNumber: "8", sex: "Female", bloodGroup: "A+" },
    { id: 9, name: "Paromita Dutta", rollNumber: "9", sex: "Female", bloodGroup: "B+" },
    { id: 10, name: "Md. Tawseef Hasan", rollNumber: "10", sex: "Male", bloodGroup: "A+" },
    { id: 11, name: "Ridita Paul", rollNumber: "11", sex: "Female", bloodGroup: "B+" },
    { id: 12, name: "Jassia Afroz Sumaiya", rollNumber: "12", sex: "Female", bloodGroup: "" },
    { id: 13, name: "Shamima Yeasmin Sumona", rollNumber: "13", sex: "Female", bloodGroup: "A+" },
    { id: 14, name: "Abu Tayab Mumen", rollNumber: "14", sex: "Male", bloodGroup: "O+" },
    { id: 15, name: "Sumiya Binte Reza", rollNumber: "15", sex: "Female", bloodGroup: "O+" },
    { id: 16, name: "Nurush Safi Khan", rollNumber: "16", sex: "Male", bloodGroup: "AB+" },
    { id: 17, name: "Md. Abrar Tazwar Islam", rollNumber: "17", sex: "Male", bloodGroup: "A+" },
    { id: 18, name: "M. Latifur Rahman", rollNumber: "18", sex: "Male", bloodGroup: "AB+" },
    { id: 19, name: "Towheda Mostafa Jawya", rollNumber: "19", sex: "Female", bloodGroup: "A+" },
    { id: 20, name: "Sanjida Khanam Setu", rollNumber: "20", sex: "Female", bloodGroup: "B+" },
    { id: 21, name: "Tangin Akhter Marena", rollNumber: "21", sex: "Female", bloodGroup: "B+" },
    { id: 22, name: "Anika Tahsin Mohima", rollNumber: "22", sex: "Female", bloodGroup: "B+" },
    { id: 23, name: "Gazi Mosammat Humaira", rollNumber: "23", sex: "Female", bloodGroup: "O+" },
    { id: 24, name: "Mashtura Haque Odri", rollNumber: "24", sex: "Female", bloodGroup: "O+" },
    { id: 25, name: "Mymona Siddiqua", rollNumber: "25", sex: "Female", bloodGroup: "O+" },
    { id: 26, name: "Faria Noor", rollNumber: "26", sex: "Female", bloodGroup: "B+" },
    { id: 27, name: "Hride Das", rollNumber: "27", sex: "Female", bloodGroup: "O+" },
    { id: 28, name: "Mst. Maesha Afrin", rollNumber: "28", sex: "Female", bloodGroup: "B+" },
    { id: 29, name: "Sadika Mahmuda", rollNumber: "29", sex: "Female", bloodGroup: "B+" },
    { id: 30, name: "Himel Das Srabon", rollNumber: "30", sex: "Male", bloodGroup: "A+" },
    { id: 31, name: "Shekh Maria Sultana", rollNumber: "31", sex: "Female", bloodGroup: "O+" },
    { id: 32, name: "Kazi Fiaz Hassan", rollNumber: "32", sex: "Male", bloodGroup: "B+" },
    { id: 33, name: "Sanjana Ahmed Promi", rollNumber: "33", sex: "Female", bloodGroup: "O+" },
    { id: 34, name: "Md. Shaifullah Rafid", rollNumber: "34", sex: "Male", bloodGroup: "O+" },
    { id: 35, name: "Afrin Ahmed Munia", rollNumber: "35", sex: "Female", bloodGroup: "" },
    { id: 36, name: "Samia Kabir", rollNumber: "36", sex: "Female", bloodGroup: "B+" },
    { id: 37, name: "Tanbir Alam", rollNumber: "37", sex: "Male", bloodGroup: "A+" },
    { id: 38, name: "Yeasmin Arafat", rollNumber: "38", sex: "Female", bloodGroup: "B+" },
    { id: 39, name: "Adrita Amin", rollNumber: "39", sex: "Female", bloodGroup: "A+" },
    { id: 40, name: "Afsana Akter Akhi", rollNumber: "40", sex: "Female", bloodGroup: "O+" },
    { id: 41, name: "Aisha Zahin Nur", rollNumber: "41", sex: "Female", bloodGroup: "B+" },
    { id: 42, name: "Nurjahan Akter Laboni", rollNumber: "42", sex: "Female", bloodGroup: "B+" },
    { id: 43, name: "Sabrina Sadiya", rollNumber: "43", sex: "Female", bloodGroup: "O+" },
    { id: 44, name: "Tasnim Akter Fayika", rollNumber: "44", sex: "Female", bloodGroup: "AB+" },
    { id: 45, name: "Naimul Islam Salman", rollNumber: "45", sex: "Male", bloodGroup: "B+" },
    { id: 46, name: "Md. Arafat Hossain Sajib", rollNumber: "46", sex: "Male", bloodGroup: "AB+" },
    { id: 47, name: "Most. Humaira Jahan", rollNumber: "47", sex: "Female", bloodGroup: "A+" },
    { id: 48, name: "Md. Masud Anam", rollNumber: "48", sex: "Male", bloodGroup: "A+" },
    { id: 49, name: "Jannatul Ferdous Warsee", rollNumber: "49", sex: "Female", bloodGroup: "AB+" },
    { id: 50, name: "Nazneen Islam", rollNumber: "50", sex: "Female", bloodGroup: "O+" },
    { id: 51, name: "Rumana Akter Borsha", rollNumber: "51", sex: "Female", bloodGroup: "B+" },
    { id: 52, name: "Rubina Azad", rollNumber: "52", sex: "Female", bloodGroup: "A+" },
    { id: 53, name: "Shahriar Zidan Zarif", rollNumber: "53", sex: "Male", bloodGroup: "A+" },
    { id: 54, name: "Sumaya Sultana Tajbin", rollNumber: "54", sex: "Female", bloodGroup: "B+" },
    { id: 55, name: "Mohaimenul Islam Arman", rollNumber: "55", sex: "Male", bloodGroup: "B+" },
    { id: 56, name: "Lamisa Tasnim", rollNumber: "56", sex: "Female", bloodGroup: "O+" },
    { id: 57, name: "Riya Mitra", rollNumber: "57", sex: "Female", bloodGroup: "A+" },
    { id: 58, name: "Bissanath Debnath", rollNumber: "58", sex: "Male", bloodGroup: "B+" },
    { id: 59, name: "Rubaiya Rahman", rollNumber: "59", sex: "Female", bloodGroup: "O+" },
    { id: 60, name: "Md. Amit Hasan Priyo", rollNumber: "60", sex: "Male", bloodGroup: "O+" },
    { id: 61, name: "Sahanima Bhuiyan Simi", rollNumber: "61", sex: "Female", bloodGroup: "O+" },
    { id: 62, name: "Tashnia Kabir Obantee", rollNumber: "62", sex: "Female", bloodGroup: "B+" },
    { id: 63, name: "Hosne Jannat Maisha", rollNumber: "63", sex: "Female", bloodGroup: "AB+" },
    { id: 64, name: "Nyema Binte Alam", rollNumber: "64", sex: "Female", bloodGroup: "O+" },
    { id: 65, name: "Maidah Sultana", rollNumber: "65", sex: "Female", bloodGroup: "B+" },
    { id: 66, name: "Taosif Ahasan Zisan", rollNumber: "66", sex: "Male", bloodGroup: "A+" },
    { id: 67, name: "Mst. Maria Sarker", rollNumber: "67", sex: "Female", bloodGroup: "O+" },
    { id: 68, name: "Abdullah Al Muhim", rollNumber: "68", sex: "Male", bloodGroup: "O+" },
    { id: 69, name: "Md. Mehedi Hasan Munna", rollNumber: "69", sex: "Male", bloodGroup: "A+" },
    { id: 70, name: "Md. Nayeem Bhuiyan", rollNumber: "70", sex: "Male", bloodGroup: "A+" },
    { id: 71, name: "Md. Sadikul Islam Shihab", rollNumber: "71", sex: "Male", bloodGroup: "AB+" },
    { id: 72, name: "Farhan Mostafiz", rollNumber: "72", sex: "Male", bloodGroup: "A+" },
    { id: 73, name: "Md. Rahatul Islam", rollNumber: "73", sex: "Male", bloodGroup: "B+" },
    { id: 74, name: "Iqra Mehjabin", rollNumber: "74", sex: "Female", bloodGroup: "B+" },
    { id: 75, name: "Sumaiya Akter", rollNumber: "75", sex: "Female", bloodGroup: "B+" },
    { id: 76, name: "Abu Souad Shamsudduha", rollNumber: "76", sex: "Male", bloodGroup: "O+" },
    { id: 77, name: "Dil Afrose Supti", rollNumber: "77", sex: "Female", bloodGroup: "O+" },
    { id: 78, name: "Jannatun Naima", rollNumber: "78", sex: "Female", bloodGroup: "A+" },
    { id: 79, name: "Md. Shahidul Islam Fuad", rollNumber: "79", sex: "Male", bloodGroup: "A+" },
    { id: 80, name: "Pranto Roy", rollNumber: "80", sex: "Male", bloodGroup: "B+" },
    { id: 81, name: "Rajaul Karim Sajib", rollNumber: "81", sex: "Male", bloodGroup: "AB+" },
    { id: 82, name: "Shofeullah Raihan", rollNumber: "82", sex: "Male", bloodGroup: "B-" },
    { id: 83, name: "Sabiha Akter Eva", rollNumber: "83", sex: "Female", bloodGroup: "AB+" },
    { id: 84, name: "Shah Muksitol Islam", rollNumber: "84", sex: "Male", bloodGroup: "AB+" },
    { id: 85, name: "Ashma-Ul-Husna", rollNumber: "85", sex: "Female", bloodGroup: "A+" },
    { id: 86, name: "Debi Rani Das", rollNumber: "86", sex: "Female", bloodGroup: "B+" },
    { id: 87, name: "Hafiz Al Asad", rollNumber: "87", sex: "Male", bloodGroup: "O+" },
    { id: 88, name: "Md. Mahmudul Hasan Joy", rollNumber: "88", sex: "Male", bloodGroup: "O+" },
    { id: 89, name: "Md. Rakib Hossain", rollNumber: "89", sex: "Male", bloodGroup: "A+" },
    { id: 90, name: "Fariha Tasneem", rollNumber: "90", sex: "Female", bloodGroup: "A+" },
    { id: 91, name: "Amrin Ahmed", rollNumber: "91", sex: "Female", bloodGroup: "O+" },
    { id: 92, name: "Md. Al Jariat Zisan", rollNumber: "92", sex: "Male", bloodGroup: "B+" },
    { id: 93, name: "Sabrina Mahmud Shahrin", rollNumber: "93", sex: "Female", bloodGroup: "O+" },
    { id: 94, name: "Nurul Fays Manon", rollNumber: "94", sex: "Male", bloodGroup: "O+" },
    { id: 95, name: "Fariza Ruhaniath Momo", rollNumber: "95", sex: "Female", bloodGroup: "A+" },
    { id: 96, name: "Md. Al Amin", rollNumber: "96", sex: "Male", bloodGroup: "O+" },
    { id: 97, name: "Mossa. Ferdowsi Akter", rollNumber: "97", sex: "Female", bloodGroup: "O+" },
    { id: 98, name: "Israt Zarin", rollNumber: "98", sex: "Female", bloodGroup: "O+" },
    { id: 99, name: "Delowar Hosen Rony", rollNumber: "99", sex: "Male", bloodGroup: "AB+" },
    { id: 100, name: "Monzur E Mowla Akash", rollNumber: "100", sex: "Male", bloodGroup: "B-" }

];


